role_netdata:
  rpm: http://repo.quintagroup.com/cblr/repo_mirror/f26-x86_64.quinta/netdata-1.7.1-1qg_rolling_184.fc26.x86_64.rpm
  systemd_units: restart_on_fail
  config:
    listen_to: 0.0.0.0
    backend:
      use: False
    master:
      use: True # This will set this server to be a Netdata Master.
      memory_mode: map # save, map, ram, none (more info in above dosc)
      history: 3600
      api_key: "bfa9a9ca-e5ba-413c-b4f1-f489d426ac5c"
    slave:
      use: False
  health_check:
    use: False
    notify:
      telegram: "431368952:AAEytzk3znpz9M3W4fPUsrQpUG0icKvk8UI"
      telegram_recipient: "358121482"

role_influx:
  graphite:
    listeners:  # set few databases using list inside 'listeners'
    - enabled: True
      database: graphite  # database name
      user: ""
      password: ""
      bind_ip: '0.0.0.0'
      bind_port: '2003'
      protocol: tcp
      batch_size: 5000  # Flush if this many points get buffered
      batch_pending: 10 # Number of batches that may be pending in memory
      batch_timeout: 1  # Flush at least this often even if we haven't hit buffer limit
      template:  # will divide incoming data into separate queries
        separator: '.' # careful with this
        tags: '["state=sandbox"]'  # at least one tag must be present
        patterns:
        - 'env.host.measurement.field*'
      retention_policy:  # delete ol data
        name: monitoring  # name of ret policy
        alter: True # if setting ret policy after database was created (second run of this role)
                     # it is needed to set 'alter: True' to force new ret policy
        duration: 10m # m minutes; h hours; d days; w weeks; INF infinite
        replication: 1  # how many replications allowed
